export interface SKU{
    productId: string;
    productName: string;
    productUP: number;
    productImg: string;
};

export const INVENTORY: SKU[] = [{'productId': '#1-acorn_squash', 'productName': 'Acorn Squash', 'productUP': 6, 'productImg': '/assets/fruits/acorn_squash.png'}, {'productId': '#2-apple', 'productName': 'Apple', 'productUP': 8, 'productImg': '/assets/fruits/apple.png'}, {'productId': '#3-bell_pepper', 'productName': 'Bell Pepper', 'productUP': 9, 'productImg': '/assets/fruits/bell_pepper.png'}, {'productId': '#4-blueberries', 'productName': 'Blueberries', 'productUP': 3, 'productImg': '/assets/fruits/blueberries.png'}, {'productId': '#5-broccoli', 'productName': 'Broccoli', 'productUP': 8, 'productImg': '/assets/fruits/broccoli.png'}, {'productId': '#6-carrot', 'productName': 'Carrot', 'productUP': 6, 'productImg': '/assets/fruits/carrot.png'}, {'productId': '#7-celery', 'productName': 'Celery', 'productUP': 7, 'productImg': '/assets/fruits/celery.png'}, {'productId': '#8-chili_pepper', 'productName': 'Chili Pepper', 'productUP': 2, 'productImg': '/assets/fruits/chili_pepper.png'}, {'productId': '#9-corn', 'productName': 'Corn', 'productUP': 5, 'productImg': '/assets/fruits/corn.png'}, {'productId': '#10-eggplant', 'productName': 'Eggplant', 'productUP': 3, 'productImg': '/assets/fruits/eggplant.png'}, {'productId': '#11-harold', 'productName': 'Harold', 'productUP': 3, 'productImg': '/assets/fruits/harold.png'}, {'productId': '#12-lettuce', 'productName': 'Lettuce', 'productUP': 1, 'productImg': '/assets/fruits/lettuce.png'}, {'productId': '#13-mushroom', 'productName': 'Mushroom', 'productUP': 0, 'productImg': '/assets/fruits/mushroom.png'}, {'productId': '#14-onion', 'productName': 'Onion', 'productUP': 5, 'productImg': '/assets/fruits/onion.png'}, {'productId': '#15-potato', 'productName': 'Potato', 'productUP': 6, 'productImg': '/assets/fruits/potato.png'}, {'productId': '#16-pumpkin', 'productName': 'Pumpkin', 'productUP': 4, 'productImg': '/assets/fruits/pumpkin.png'}, {'productId': '#17-radish', 'productName': 'Radish', 'productUP': 1, 'productImg': '/assets/fruits/radish.png'}, {'productId': '#18-squash', 'productName': 'Squash', 'productUP': 9, 'productImg': '/assets/fruits/squash.png'}, {'productId': '#19-strawberry', 'productName': 'Strawberry', 'productUP': 8, 'productImg': '/assets/fruits/strawberry.png'}, {'productId': '#20-sugar_snap', 'productName': 'Sugar Snap', 'productUP': 2, 'productImg': '/assets/fruits/sugar_snap.png'}, {'productId': '#21-tomato', 'productName': 'Tomato', 'productUP': 4, 'productImg': '/assets/fruits/tomato.png'}, {'productId': '#22-zucchini', 'productName': 'Zucchini', 'productUP': 6, 'productImg': '/assets/fruits/zucchini.png'}]

